CREATE DATABASE IF NOT EXISTS pokecollector CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE pokecollector;

CREATE TABLE IF NOT EXISTS utenti(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    data_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS espansioni(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS carte(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    immagine_url TEXT,
    espansione_id INT,
    numero_carta VARCHAR(20),
    FOREIGN KEY (espansione_id) REFERENCES espansioni(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS collezioni(
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_utente INT NOT NULL,
    id_carta INT NOT NULL,
    quantita INT DEFAULT 1,
    data_aggiunta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_utente) REFERENCES utenti(id) ON DELETE CASCADE,
    FOREIGN KEY (id_carta) REFERENCES carte(id) ON DELETE CASCADE
);