CREATE DATABASE IF NOT EXISTS pokecollector CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE pokecollector;

CREATE TABLE IF NOT EXISTS utenti(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    data_registrazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remember_token VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS collezioni(
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_utente INT NOT NULL,
    id_carta VARCHAR(255) NOT NULL,
    quantita INT DEFAULT 1,
    data_aggiunta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_utente) REFERENCES utenti(id) ON DELETE CASCADE
);